// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxhI-okPea8Na5sU8oCFTVq3XjV9NPlks',
    appId: '1:919029163097:web:fc5521fbe1b2ec01513d48',
    messagingSenderId: '919029163097',
    projectId: 'coffeeapp-cad10',
    authDomain: 'coffeeapp-cad10.firebaseapp.com',
    storageBucket: 'coffeeapp-cad10.appspot.com',
    measurementId: 'G-XLCL0P5GT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVbp94uoQH9LHDATIqoPuNPShjaEB9JVU',
    appId: '1:919029163097:android:905b043d29ae6bab513d48',
    messagingSenderId: '919029163097',
    projectId: 'coffeeapp-cad10',
    storageBucket: 'coffeeapp-cad10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx2Ve7bGd9PR2VCGgZWYWdPCN7bcAQRzQ',
    appId: '1:919029163097:ios:237cc42bc4e0e5ff513d48',
    messagingSenderId: '919029163097',
    projectId: 'coffeeapp-cad10',
    storageBucket: 'coffeeapp-cad10.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );

}